script: "bundle exec rake test && bundle exec cucumber features"
rvm:
#  - 1.8.6 # Has trouble with rake 0.9+ :(
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx
  - jruby
notifications:
  email:
    on_success: always
    on_failure: always
